import React from "react";
import Head from "next/head";
import Navbar from "./Navbar";
import Footer from "./Footer";
const Layout = ({ children }) => {
	return (
		<>
			<Head>
				<title>Jim</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				<Navbar />
				{children}
				<Footer />
			</main>
		</>
	);
};

export default Layout;
